# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
